# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

# Load Dunst Notification Manager
exec-once = dunst

# Set Cursor Theme
exec-once = hyprctl setcursor Bibata-Rainbow-Modern 20

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Initialize swww
exec-once = swww query || swww init && swww clear 111111

# Set wallpaper
exec-once = ~/scripts/wallpaper.sh

# Load ianny
exec-once = ianny
