# -------------------#
# Keyboard shortcuts-#
# -------------------#

$s = SUPER
$a = ALT

bind = $s, return, exec, gtk-launch kitty.desktop
bind = $s, C, killactive
bind = $s, F, fullscreen
bind = $s, G, exec, gtk-launch thorium-browser.desktop
bind = $s, E, exec, ~/.config/hypr/ranger.sh
bind = $s, A, centerwindow
bind = $s, D, pin
bind = SUPERSHIFT, U, exec, ~/scripts/updatewal-swww.sh
bindr = $s, R, exec, pkill rofi || rofi -show drun
bindr = $s, Q, exec, pkill rofi || rofi -show calc -modi calc -no-show-match -no-sort -calc-command "echo -n '{result}' | wl-copy"
bind  = $s, TAB, exec, pkill rofi || rofi -show window
bind = CONTROLALT, Delete, exec, ~/.config/rofi/powermenu/type-1/powermenu.sh
bind = CONTROLALT, Escape, exec, wlogout
bind = $s, P, pseudo, # dwindle
bind = $s, V, togglefloating,
bind = $s, J, togglesplit, # dwindle
bind = $s, L, exec, swaylock
bind = SUPER,B,bringactivetotop
bind = SUPERSHIFT, B, exec, ~/.config/waybar/launch.sh
bind = $s, M, exit,
# Move focus with s + arrow keys
binde = $s, left, movefocus, l
binde = $s, right, movefocus, r
binde = $s, up, movefocus, u
binde = $s, down, movefocus, d

# Move windows with a + arrow keys
bind  = $a, left, movewindow, l
binde = $a, left, moveactive, -50 0
bind  = $a, right, movewindow, r
binde = $a, right, moveactive, 50 0
bind  = $a, up, movewindow, u
binde = $a, up, moveactive, 0 -50
bind  = $a, down, movewindow, d
binde = $a, down, moveactive, 0 50
# Switch workspaces with s + [0-9]
bind = $s, 1, workspace, 1
bind = $s, 2, workspace, 2
bind = $s, 3, workspace, 3
bind = $s, 4, workspace, 4
bind = $s, 5, workspace, 5
bind = $s, 6, workspace, 6
bind = $s, 7, workspace, 7
bind = $s, 8, workspace, 8
bind = $s, 9, workspace, 9
bind = $s, 0, workspace, 10
binde = $a, TAB, workspace, e+1

# Move active window to a workspace with s + SHIFT + [0-9]
bind = $s SHIFT, 1, movetoworkspace, 1
bind = $s SHIFT, 2, movetoworkspace, 2
bind = $s SHIFT, 3, movetoworkspace, 3
bind = $s SHIFT, 4, movetoworkspace, 4
bind = $s SHIFT, 5, movetoworkspace, 5
bind = $s SHIFT, 6, movetoworkspace, 6
bind = $s SHIFT, 7, movetoworkspace, 7
bind = $s SHIFT, 8, movetoworkspace, 8
bind = $s SHIFT, 9, movetoworkspace, 9
bind = $s SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with s + scroll
bind = $s, mouse_down, workspace, e+1
bind = $s, mouse_up, workspace, e-1

# Move/resize windows with s + LMB/RMB and dragging
bindm = $s, mouse:272, movewindow
bindm = $s, mouse:273, resizewindow

# Resizing windows
binde = $s SHIFT, left,  resizeactive, -50 0
binde = $s SHIFT, right, resizeactive, 50 0
binde = $s SHIFT, up,    resizeactive, 0 -50
binde = $s SHIFT, down,  resizeactive, 0 50

# Screenshot with hyprshot
bind = SHIFT, Print, exec, hyprshot -m window
bind = , Print, exec, hyprshot -m region

bind  = ,XF86AudioPlay,         exec, playerctl play-pause
bind  = ,XF86AudioStop,         exec, playerctl stop
bind  = ,XF86AudioPrev,         exec, playerctl previous
bind  = ,XF86AudioNext,         exec, playerctl next
bindle =, XF86AudioLowerVolume, exec, pamixer -d 10
bindle =, XF86AudioRaiseVolume, exec, pamixer -i 10
bind =, XF86AudioMute, exec, pamixer -t
bind =, XF86AudioMicMute, exec, pamixer --default-source -t
bindle =, XF86MonBrightnessUp, exec, brightnessctl set 100+
bindle =, XF86MonBrightnessDown, exec, brightnessctl set 100-


bind=SUPERSHIFT,Z,exec,pypr toggle term && hyprctl dispatch bringactivetotop
bind=SUPERSHIFT,F,exec,killall pavucontrol && pypr toggle pavucontrol && hyprctl dispatch bringactivetotop
