# ----------------------------------------------------- 
# General window layout and colors
# ----------------------------------------------------- 
general {
    layout = dwindle
    no_focus_fallback = true
    resize_on_border = true
}
