[".config/NeutronVim"]
type = "git-repo"
url = "https://github.com/daUnknownCoder/NeutronVim"
[".config/AstroNvim"]
type = "git-repo"
url = "https://github.com/AstroNvim/AstroNvim"
[".config/LazyVim"]
type = "git-repo"
url = "https://github.com/LazyVim/LazyVim"
[".config/NvChad"]
type = "git-repo"
url = "https://github.com/NvChad/NvChad"
[".config/Kickstart"]
type = "git-repo"
url = "https://github.com/nvim-lua/kickstart.nvim"
