#Fonts :
font_family Ellograph CF
bold_font JetBrainsMono Nerd Font
italic_font Cascursive
bold_italic_font Fisa Code
font_size 10

#Ligatures :
disable_ligatures active never
disable_ligatures all never
disable_ligatures tab never

#Opening URLs :
open_url_with thorium-browser
url_style double

#Copy :
copy_on_select clipboard

#Opacity :
background_opacity 0.6
draw_minimal_borders yes
window_padding_width 2
window_border_width 2
hide_window_decorations yes
# active_border_color none

#tabs
tab_bar_edge top
# tab_bar_background none
tab_bar_style fade
tab_fade 1
tab_powerline_style slanted
tab_title_template "{fmt.fg.c2c2c2}{title}"
confirm_os_window_close 0

active_tab_title_template "{fmt.fg._fff}{title}"
# active_tab_foreground #fff
active_tab_font_style bold-italic
# active_tab_background #8631B4
# inactive_tab_foreground #c2c2c2
# inactive_tab_background #8631B4

#Gruvbox :
# foreground #ebdbb2
# background #272727
# selection_foreground #655b53
# selection_background #ebdbb2
# url_color #db5c0d
# cursor #8fee96
cursor_shape block

# The i6 terminal colors

#black
# color0 #2f2f2f
# color8 #656565

#red
# color1 #d75f5f
# color9 #d75f5f

#green
# color2 #d4d232
# color10 #8fee96

#yellow
# color3 #af865a
# color11 #cd950c

#blue
# color4 #22c3a1
# color12 #22c3a1

#magenta
# color5 #775759
# color13 #775759

#cyan
# color6 #84ebd9
# color14 #84ebd9

#white
# color7 #c0b18b
# color15 #c0b18b

# Added by Gogh
include colors.conf


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
