/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP, lightColors } from './settings/theme.js';

export default [
    Theme({
        name: 'Kitty Dark',
        icon: '󰄛',
        'desktop.wallpaper.img': WP + 'kittybl.jpeg',
    }),
    Theme({
        name: 'Kitty Light',
        icon: '󰄛',
        'desktop.wallpaper.img': WP + 'kitty.jpeg',
        ...lightColors,
        'theme.widget.bg': '$accent',
        'theme.widget.opacity': 64,
    }),
    Theme({
        name: 'Leaves',
        icon: '󰌪',
        'desktop.wallpaper.img': WP + 'leaves.jpg',
        'theme.accent.accent': '$green',
        'theme.accent.gradient': 'to right, $accent, darken($accent, 14%)',
        'theme.widget.opacity': 92,
        'border.opacity': 86,
        'theme.bg': 'transparentize(#171717, 0.3)',
        'bar.style': 'floating',
        radii: 0,
    }),
    Theme({
        name: 'Ivory',
        icon: '󰟆',
        ...lightColors,
        'desktop.wallpaper.img': WP + 'ivory.png',
        'desktop.wallpaper.fg': '$bg_color',
        'desktop.screen_corners': false,
        'bar.style': 'separated',
        'theme.widget.bg': '$accent',
        'theme.widget.opacity': 64,
        'desktop.drop_shadow': false,
        'border.width': 2,
        'border.opacity': 0,
        'theme.accent.gradient': 'to right, $accent, darken($accent, 6%)',
        'hypr.inactive_border': 'rgba(111111FF)',
        'bar.separators': false,
    }),
    Theme({
        name: 'Space',
        icon: '',
        'desktop.wallpaper.img': WP + 'space.jpg',
        spacing: 11,
        padding: 10,
        radii: 12,
        'theme.accent.accent': '$magenta',
        'desktop.screen_corners': false,
        'desktop.clock.enable': false,
        'bar.separators': false,
        'bar.icon': '',
        'theme.bg': 'transparentize(#171717, 0.3)',
        'theme.widget.opacity': 95,
        'bar.flat_buttons': false,
    }),
    Theme({
        name: 'daUnknownCoder',
        icon: ' ',
        spacing: 6,
        padding: 9,
        radii: 10,
        popover_padding_multiplier: 1.4,
        'color.red': '#e55f86',
        'color.green': '#00D787',
        'color.yellow': '#EBFF71',
        'color.blue': '#51a4e7',
        'color.magenta': '#9077e7',
        'color.teal': '#51e6e6',
        'color.orange': '#E79E64',
        'theme.scheme': 'dark',
        'theme.bg': 'transparentize(#171717, 0.3)',
        'theme.fg': '#eeeeee',
        'theme.accent.accent': '$magenta',
        'theme.accent.fg': '#141414',
        'theme.accent.gradient': 'to right, $accent, lighten($accent, 6%)',
        'theme.widget.bg': '$fg-color',
        'theme.widget.opacity': 75,
        'border.color': '$fg-color',
        'border.opacity': 90,
        'border.width': 3,
        'hypr.inactive_border': 'rgba(ffCDFFF6)',
        'hypr.wm_gaps_multiplier': 2.4,
        'font.font': 'Abel 10',
        'font.mono': 'Mononoki Nerd Font',
        'font.size': 11,
        'applauncher.width': 500,
        'applauncher.height': 500,
        'applauncher.icon_size': 52,
        'bar.position': 'top',
        'bar.style': 'normal',
        'bar.flat_buttons': true,
        'bar.separators': false,
        'bar.icon': '',
        'battery.bar.width': 100,
        'battery.bar.height': 12,
        'battery.low': 10,
        'battery.medium': 30,
        'battery.high': 95,
        'desktop.wallpaper.fg': '#fff',
        'desktop.wallpaper.img':
            '/home/daUnknownCoder/wallpaper/_1e6fbbf2-3152-4d22-af9c-ec6383173b9e.jpeg',
        'desktop.avatar':
            '/home/daUnknownCoder/wallpaper/_97106f1a-b362-4215-831c-3e2ace0cfde7.jpeg',
        'desktop.screen_corners': false,
        'desktop.clock.enable': true,
        'desktop.clock.position': 'center center',
        'desktop.drop_shadow': true,
        'desktop.shadow': 'rgba(0, 0, 0, .6)',
        'desktop.dock.icon_size': 55,
        'desktop.dock.pinned_apps': [
            'Thorium-browser',
            'org.wezfurlong.wezterm',
            'org.gnome.Nautilus',
            'org.gnome.Calendar',
            'obsidian',
            'transmission-gtk',
            'caprine',
            'teams-for-linux',
            'discord',
            'spotify',
            'com.usebottles.bottles',
            'org.gnome.Software',
        ],
        'notifications.black_list': ['Spotify'],
        'notifications.position': ['top'],
        'notifications.width': 450,
        'dashboard.sys_info_size': 70,
        'mpris.black_list': ['Caprine'],
        'mpris.preferred': 'spotify',
        workspaces: 10,
    }),
];
