# ----------------------------------------------------- 
# General window decoration
# ----------------------------------------------------- 
decoration {
    rounding = 20
    blur {
        enabled = true
        size = 2
        passes = 1
        new_optimizations = true
        # blurls = waybar
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
    active_opacity = 1.2
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0
    dim_inactive = true
}
